# config/policies.yml
max_ink_coverage: 300

# Rich blacks by workflow
rich_black_sheetfed: "50/40/40/100"
rich_black_wide: "75/75/75/100"

# Global prepress mins (apply to ALL jobs)
min_bleed_in: 0.125
min_safety_in: 0.25

# Wide-format defaults
grommet_spacing_default_in: 12
allow_rgb_assets_wide: true

# Soft-nags toggles
soft_nags:
  enable: true
  adjustments: true       # tell me when we auto-raised bleed/safety
  grommets: true          # remind to confirm grommet spacing on wide-format
  icc_missing: false       # nudge when no ICC found and a default is assumed

# Optional misc rules
min_stroke_pt: 0.25
min_text_pt:
  positive: 6
  knockout: 8
overprint_rules:
  small_100K_text_under_pt: 10

# A default ICC if nothing else is specified
default_icc: "US Web Coated (SWOP) v2"
