business_card:
  bleed_in: 0.125
  safety_in: 0.125
  color_mode: "CMYK"

trifold:
  bleed_in: 0.125
  safety_in: 0.125
  fold_style: "roll"

banner:
  bleed_in: 0.0
  safety_in: 0.5
  min_ppi: 200
  allow_rgb: true
  icc_profile: "GRACoL 2013"
  grommet_margin_in: 0.5
  grommet_spacing_in: 12
  finishing:
    hems:
      all_sides: 1.0   # fold width in inches
    pole_pocket:
      top: { depth_in: 3.0 }  # if used
    grommet:
      diameter_in: 0.375
      corners_only: false

poster:
  bleed_in: 0.125
  safety_in: 0.25
  min_ppi: 200
  allow_rgb: true
  icc_profile: "GRACoL 2013"
